// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApSqJEgSVYhdDFpARzGGTmL8m6a3rg418',
    appId: '1:774395471357:web:0439b83ad5cccd04266594',
    messagingSenderId: '774395471357',
    projectId: 'mrpostsboard',
    authDomain: 'mrpostsboard.firebaseapp.com',
    storageBucket: 'mrpostsboard.firebasestorage.app',
    measurementId: 'G-GS57BSFM4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbtnhnLCVkET8WbAnAcHM0EC-jO_kBDKQ',
    appId: '1:774395471357:android:fdcefc720259b4b8266594',
    messagingSenderId: '774395471357',
    projectId: 'mrpostsboard',
    storageBucket: 'mrpostsboard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxB2Vfsn2TEoDAmaXbYynz52LIIQ5wlqA',
    appId: '1:774395471357:ios:a6dd959dbdf3b540266594',
    messagingSenderId: '774395471357',
    projectId: 'mrpostsboard',
    storageBucket: 'mrpostsboard.firebasestorage.app',
    iosBundleId: 'com.marcusrohden.mrpostsboard',
  );
}
